spring:
  datasource:
    url: jdbc:mysql://localhost:3306/love_admin?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
    username: sentinel
    password: sentinel-dev
  jpa:
    hibernate.dll-auto: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true

  logging:
    level:
      org.springframework: error
      org.hibernate: error
      org.hibernate.SQL: error
      org.hibernate.type.descriptor.sql.BasicBinder: error
      io.oenomel.sentinel: debug
